[package]
name = "thrum-engine"
authors = ["RedCatstone"]
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
derive_more = { version = "2.1.1", features = ["display", "error"] }
strum_macros = "0.28.0"  # using EnumString for pretty_printing

[lib]
name = "thrum_engine"
path = "src/lib.rs"

[lints]
workspace = true