[package]
name = "thrum-engine"
version = "0.1.0"
edition = "2024"
authors = ["RedCatstone"]
license = "MIT"

[dependencies]
derive_more = { version = "2.1.1", features = ["display", "error"] }
strum_macros = "0.28.0"  # using EnumString for pretty_printing

[lib]
name = "thrum_engine"
path = "src/lib.rs"

[lints.clippy]
# --- Groups ---
all = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }

# --- Specific Allows ---
missing_panics_doc = "allow"
missing_errors_doc = "allow"
too_many_lines = "allow"  # i am like 4x over clippies limits OOOPSS lol
derive_partial_eq_without_eq = "allow"  # don't care
equatable_if_let = "allow"  # i fully disagree with this lint, i think pattern matching is actually cleaner